### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by shreysaroch** [ghoullier/ng-image-cache#3]
Documentation not clear as to how data should be saved and how image should be retrieved.
Should include examples.

**Comment by ghoullier** [comment]
Hi!

Indeed readme doesn't explain how images are serialized. ngImageCache use canvas data url API to generate a base64 image representation see https://github.com/ghoullier/ng-image-cache/blob/master/src/services/data.js#L34

**Comment by shreysaroch** [comment]
Hi @ghoullier . We are trying to integrate the module but somehow it seems the data is not being loaded. It shows a empty screen. Can you include a exmaple as to how to retrieve the data. Also we can see that in localstorage(which we have set as storage) the key is same as the value i.e. both are url. should not it be saving the base64 version of the image?

**Comment by ghoullier** [comment]
Is there a simple example which integrate localStorage https://jsfiddle.net/h993k68b/3/

**Comment by shreysaroch** [comment]
@ghoullier I ran the fiddle. Image loads fine. I turned off internet . rerun the fiddle, nothing is shown. Is that how caching is supposed to work?
perhaps you can answer the quesion: http://stackoverflow.com/questions/39833730/ng-image-cache-not-working

**Comment by ghoullier** [comment]
I answered to your problem on stackoverflow. Thanks for question.
