### ISSUE TITLE
set scope variable as data-src

### ISSUE THREAD

**Issue by bonar** [ghoullier/ng-image-cache#4]
I'd like to set parent scope variable as url like this:

```
  .controller('TestController', ['$scope', function($scope) {
    $scope.url = '//angularjs.org/img/AngularJS-large.png';
  }]);
```

```
    <div ng-controller="TestController">
      <ui-image data-src="{{url}}" data-title="title"></ui-image>
    </div>
```

I think it doesn't work because {{url}} is set as url without evaluation.
Do you have a plan to support this use case? like this:

https://github.com/bonar/ng-image-cache/commit/35d8e914f935272673c2ed4657b993eb8c54eca6

I'm sorry if I misunderstood. I would be happy if you could tell me if there is a better way.
Thank you for great directive.

**Comment by ghoullier** [comment]
Hi!

First of all thank you to report this issue.

I'll introduce this new feature in 0.4 release.

**Comment by ghoullier** [comment]
Fixed by https://github.com/ghoullier/ng-image-cache/commit/f508a3cb00f8be0ba0b5889f754b92b403a17880

**Comment by bonar** [comment]
Thanks for yout implementation!
